-- Generated by AutomateDV (formerly known as dbtvault)
WITH source_data AS (
    SELECT *
    FROM "dbtvault_db"."development"."ORDERS"
),
derived_columns AS (
    SELECT
    o_custkey AS CUSTOMER_ID,
    '1998-01-01' AS LOAD_DATETIME,
    'TPCH_ORDERS' AS RECORD_SOURCE
    FROM source_data
),
hashed_columns AS (
    SELECT
    CUSTOMER_ID,
    LOAD_DATETIME,
    RECORD_SOURCE,
    DECODE(MD5(NULLIF(UPPER(TRIM(CAST(o_custkey AS VARCHAR))), '')), 'hex') AS CUSTOMER_HK
    FROM derived_columns
),
columns_to_select AS (
    SELECT
    CUSTOMER_ID,
    LOAD_DATETIME,
    RECORD_SOURCE,
    CUSTOMER_HK
    FROM hashed_columns
)
SELECT * FROM columns_to_select