-- Generated by AutomateDV (formerly known as dbtvault)
WITH source_data AS (
    SELECT *
    FROM "dbtvault_db"."development"."CUSTOMER"
),
columns_to_select AS (
    SELECT
    FROM source_data
)
SELECT * FROM columns_to_select