-- Generated by AutomateDV (formerly known as dbtvault)
WITH source_data AS (
    SELECT *
    FROM "dbtvault_db"."development"."CUSTOMER"
),
null_columns AS (
    SELECT
    C_CUSTKEY AS C_CUSTKEY_ORIGINAL,
        COALESCE(C_CUSTKEY, '-1') AS C_CUSTKEY,
    C_NATIONKEY AS C_NATIONKEY_ORIGINAL,
        COALESCE(C_NATIONKEY, '-2') AS C_NATIONKEY
    FROM source_data
),
columns_to_select AS (
    SELECT
    C_CUSTKEY,
    C_CUSTKEY_ORIGINAL,
    C_NATIONKEY,
    C_NATIONKEY_ORIGINAL
    FROM null_columns
)
SELECT * FROM columns_to_select