version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

formats: all

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"