site_name: dbtvault
site_author: Datavault
site_dir: 'site'
repo_name: 'Datavault-UK/dbtvault'
site_url: 'https://dbtvault.readthedocs.io/'
repo_url: 'https://github.com/Datavault-UK/dbtvault'
dev_addr: 127.0.0.1:8001
edit_uri: ""

theme:
  name: 'material'
  custom_dir: 'overrides'
  show_sidebar: true
  logo: 'assets/images/logo.png'
  banner: 'assets/images/docs-banner.png'
  favicon: 'assets/images/favicon.ico'
  palette:
    - scheme: material
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  highlightjs: true
  features:
    - navigation.top
    - navigation.indexes

nav:
  - Home: 'index.md'
  - Tutorials:
      - Getting Started: 'tutorial/index.md'
      - Staging: 'tutorial/tut_staging.md'
      - Hubs: 'tutorial/tut_hubs.md'
      - Links: 'tutorial/tut_links.md'
      - Transactional Links: 'tutorial/tut_t_links.md'
      - Satellites: 'tutorial/tut_satellites.md'
      - Effectivity Satellites: 'tutorial/tut_eff_satellites.md'
      - Multi-Active Satellites: 'tutorial/tut_multi_active_satellites.md'
      - Extended Tracking Satellites: 'tutorial/tut_xts.md'
      - As of Date Tables: 'tutorial/tut_as_of_date.md'
      - Point In Time (PIT) tables: 'tutorial/tut_point_in_time.md'
      - Bridge Tables: 'tutorial/tut_bridges.md'
  - Worked example:
      - Getting Started: 'worked_example/index.md'
      - Project setup: 'worked_example/we_setup.md'
      - Profiling TPC-H: 'worked_example/we_tpch_profile.md'
      - Creating the stage layers: 'worked_example/we_staging.md'
      - Loading the vault: 'worked_example/we_loading.md'
  - Metadata Reference: 'metadata.md'
  - Macros:
      - 'macros/index.md'
      - Stage Macro Configurations: 'macros/stage_macro_configurations.md'
  - Materialisations: 'materialisations.md'
  - Best Practices:
      - 'best_practises/index.md'
      - Hashing: 'best_practises/hashing.md'
      - Escaping: 'best_practises/escaping.md'
      - NULL Handling: 'best_practises/null_handling.md'
      - Loading: 'best_practises/loading.md'
      - Materialisations: 'best_practises/materialisations.md'
  - Migration Guides: 'migration_guides.md'
  - Extending: 'extending.md'
  - Roadmap: 'roadmap.md'
  - Versions: 'versions.md'
  - Changelog:
      - Stable Releases: 'changelog/index.md'
      - Beta Releases: 'changelog/beta.md'
  - Contributing:
      - Getting Started: 'contributing/index.md'
      - Style Guides:
          - Tutorials: 'contributing/style_guides/tutorials.md'
  - Licence: 'LICENSE.md'
  - Find Us:
      - GitHub: 'https://github.com/Datavault-UK/dbtvault'
      - Facebook: 'https://www.facebook.com/DataVaultUK/'
      - Twitter: 'https://twitter.com/datavault_uk'
      - LinkedIn: 'https://www.linkedin.com/company/business-thinking-limited'
      - Slack: 'https://join.slack.com/t/dbtvault/shared_invite/enQtODY5MTY3OTIyMzg2LWJlZDMyNzM4YzAzYjgzYTY0MTMzNTNjN2EyZDRjOTljYjY0NDYyYzEwMTlhODMzNGY3MmU2ODNhYWUxYmM2NjA'
      - Data Vault User Group: 'https://www.ukdatavaultusergroup.co.uk/'
      - Data Vault User Group Forums: 'https://forum.ukdatavaultusergroup.co.uk/'
      - YouTube: 'https://www.youtube.com/channel/UCdhSsZWTwkX1-v8EX84WLYg'
      - Datavault Website: 'https://www.data-vault.com/'

extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.data-vault.co.uk'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Datavault-UK/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/datavault_uk'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/DataVaultUK/'

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - abbr
  - md_in_html
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
  - toc:
      permalink: true
      toc_depth: 1-3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/all.css'
  - 'stylesheets/icons.css'

copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2022 - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of dbt labs
