site_name: dbtvault
site_author: Datavault
site_dir: 'site'
repo_name: 'Datavault-UK/dbtvault'
repo_url: 'https://github.com/Datavault-UK/dbtvault'

theme:
    name: 'material'
    custom_dir: 'theme'
    show_sidebar: true
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true


nav:
  - Home: 'index.md'
  - Metadata: 'metadata.md'
  - Walk-through guide:
      - Getting Started: 'walkthrough/wt_getting_started.md'
      - Staging: 'walkthrough/wt_staging.md'
      - Hubs: 'walkthrough/wt_hubs.md'
      - Links: 'walkthrough/wt_links.md'
      - Satellites: 'walkthrough/wt_satellites.md'
      - Transactional Links: 'walkthrough/wt_t_links.md'
      - Effectivity Satellites: 'walkthrough/wt_eff_sats.md'
  - Worked example:
    - Getting Started: 'worked_example/we_worked_example.md'
    - Project setup: 'worked_example/we_setup.md'
    - Profiling TPC-H: 'worked_example/we_tpch_profile.md'
    - Creating the stage layers: 'worked_example/we_staging.md'
    - Loading the vault: 'worked_example/we_loading.md'
  - Migration Guides:
    - Migrating from v0.4 to v0.5: 'migration_guides/migrating_v0.4_v0.5.md'
    - Migrating from v0.5 to v0.6: 'migration_guides/migrating_v0.5_v0.6.md'
  - Macros: 'macros.md'
  - Best Practices: 'best_practices.md'
  - Extending: 'extending.md'
  - Roadmap: 'roadmap.md'
  - Changelog:
    - Stable Releases: 'changelog/changelog.md'
    - Beta Releases: 'changelog/changelog_beta.md'
  - Contributing: 'contributing.md'
  - Licence: 'LICENSE.md'

extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.data-vault.co.uk'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Datavault-UK/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/datavault_uk'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/DataVaultUK/'
  version: 0.5
  req_dbt_version: 0.15.x

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true
      toc_depth: 1-3

plugins:
  - search

extra_css:
  - 'stylesheets/extra.css'

copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2020 - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of Fishtown Analytics
