site_name: dbtvault
site_author: Datavault
site_dir: 'site'
repo_name: 'Datavault-UK/dbtvault'
site_url: 'https://dbtvault.readthedocs.io/'
repo_url: 'https://github.com/Datavault-UK/dbtvault'
dev_addr: 127.0.0.1:8001
theme:
    name: 'material'
    custom_dir: 'overrides'
    show_sidebar: true
    logo: 'assets/images/logo.png'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      primary: 'black'
      accent: 'indigo'
    highlightjs: true
    features:
      - navigation.top
nav:
  - Home: 'index.md'
  - Tutorials:
      - Getting Started: 'tutorial/tut_getting_started.md'
      - Staging: 'tutorial/tut_staging.md'
      - Hubs: 'tutorial/tut_hubs.md'
      - Links: 'tutorial/tut_links.md'
      - Transactional Links: 'tutorial/tut_t_links.md'
      - Satellites: 'tutorial/tut_satellites.md'
      - Effectivity Satellites: 'tutorial/tut_eff_satellites.md'
      - Multi Active Satellites: 'tutorial/tut_multi_active_satellites.md'
      - Extended Record Tracking Satellites: 'tutorial/tut_xts.md'
      - Point in Time (PITs): 'tutorial/tut_point_in_time.md'
      - Bridges: 'tutorial/tut_bridges.md'
  - Worked example:
      - Getting Started: 'worked_example/we_worked_example.md'
      - Project setup: 'worked_example/we_setup.md'
      - Profiling TPC-H: 'worked_example/we_tpch_profile.md'
      - Creating the stage layers: 'worked_example/we_staging.md'
      - Loading the vault: 'worked_example/we_loading.md'
  - Migration Guides:
      - Migrating from v0.5 to v0.6: 'migration_guides/migrating_v0.5_v0.6.md'
      - Migrating from v0.4 to v0.5: 'migration_guides/migrating_v0.4_v0.5.md'
  - Metadata Reference: 'metadata.md'
  - Macros: 'macros.md'
  - Best Practices: 'best_practices.md'
  - Extending: 'extending.md'
  - Roadmap: 'roadmap.md'
  - Changelog:
      - Stable Releases: 'changelog/stable.md'
      - Beta Releases: 'changelog/beta.md'
  - Contributing: 'contributing.md'
  - Licence: 'LICENSE.md'

extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.data-vault.co.uk'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Datavault-UK/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/datavault_uk'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/business-thinking-limited'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/DataVaultUK/'

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
  - toc:
      permalink: true
      toc_depth: 1-3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
#  - with-pdf:
#      copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2021
#      cover_title: dbtvault Docs
#      cover_subtitle: By Datavault

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/all.css'

copyright: dbtvault and documentation &copy; Business Thinking trading as Datavault 2021 - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of dbt labs
