version: 1

staging:
  primed_stages:
    - model_name: stg_customer
      source_model: CUSTOMER
      hashed_columns:
        CUSTOMER_HK: c_custkey
        ORDER_HK: ORDER_ID
        CUSTOMER_ORDER_HK:
          - c_custkey
          - "!1"
      derived_columns:
        ORDER_ID: "!1"
        CUSTOMER_ID: c_custkey
        CUSTOMER_PHONE_LOCATOR_ID: "1"
        LOAD_DATETIME: "!1998-07-01"
        EFFECTIVE_FROM: "!1998-01-01"
        START_DATE: "!1998-01-01"
        END_DATE: "!1998-01-01"
        RECORD_SOURCE: "!TPCH_ORDERS"

    - model_name: stg_orders
      source_model: ORDERS
      hashed_columns:
        CUSTOMER_HK: o_custkey
      derived_columns:
        CUSTOMER_ID: o_custkey
        LOAD_DATETIME: "!1998-01-01"
        RECORD_SOURCE: "!TPCH_ORDERS"

    - model_name: stg_transactions
      source_model: ORDERS
      derived_columns:
        CUSTOMER_ID: o_custkey
        ORDER_ID: o_orderkey
        LOAD_DATETIME: "!1998-07-01"
        EFFECTIVE_FROM: "!1998-01-01"
        RECORD_SOURCE: "!TPCH_ORDERS"
      hashed_columns:
        TRANSACTION_HK:
          - 'CUSTOMER_ID'
          - 'ORDER_ID'
        CUSTOMER_HK: 'CUSTOMER_ID'
        ORDER_HK: 'ORDER_ID'
