name: 'docs_snippets'
version: '1.0.0'
config-version: 2

profile: 'docs_snippets'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

models:
  docs_snippets:
    raw_vault:
      materialized: incremental