-- Generated by AutomateDV (formerly known as dbtvault)
WITH source_data AS (
    SELECT *
    FROM ALEX_HIGGS.AUTOMATE_DV_DOCS_SAMPLES.CUSTOMER
),
hashed_columns AS (
    SELECT
    ,
    CAST(MD5_BINARY(NULLIF(UPPER(TRIM(CAST(C_CUSTKEY AS VARCHAR))), '')) AS BINARY(16)) AS CUSTOMER_HK
    FROM source_data
),
columns_to_select AS (
    SELECT
    CUSTOMER_HK
    FROM hashed_columns
)
SELECT * FROM columns_to_select